package com.hiking.treasure.tools;

import com.hiking.treasure.common.api.ErrorCode;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public final class ErrorCodeTsExporter {

    private ErrorCodeTsExporter() {
    }

    public static void main(String[] args) throws Exception {
        Path output = args != null && args.length > 0
                ? Path.of(args[0])
                : Path.of("docs/frontend-error-keys.ts");
        Files.createDirectories(output.getParent());
        Files.writeString(output, generateTsContent(), StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING);
    }

    public static String generateTsContent() {
        String errorKeys = Arrays.stream(ErrorCode.values())
                .map(errorCode -> "  " + errorCode.name() + ": '" + errorCode.getKey() + "',")
                .collect(Collectors.joining("\n"));

        String labels = Arrays.stream(ErrorCode.values())
                .map(errorCode -> "  " + errorCode.name() + ": '" + escapeTs(errorCode.getDefaultMessage()) + "',")
                .collect(Collectors.joining("\n"));

        String authKeys = toScopeArray(ErrorCode.Scope.AUTH);
        String passwordKeys = toScopeArray(ErrorCode.Scope.PASSWORD);
        String deleteConflictKeys = toScopeArray(ErrorCode.Scope.DELETE_CONFLICT);

        return """
                /**
                 * Generated by com.hiking.treasure.tools.ErrorCodeTsExporter.
                 * Do not edit manually.
                 */

                export const ERROR_KEYS = {
                %s
                } as const;

                export type ErrorKey = (typeof ERROR_KEYS)[keyof typeof ERROR_KEYS];

                export const AUTH_ERROR_KEYS: ErrorKey[] = [
                %s
                ];

                export const PASSWORD_ERROR_KEYS: ErrorKey[] = [
                %s
                ];

                export const DELETE_CONFLICT_ERROR_KEYS: ErrorKey[] = [
                %s
                ];

                export const ERROR_KEY_LABELS: Record<ErrorKey, string> = {
                %s
                };
                """.formatted(errorKeys, authKeys, passwordKeys, deleteConflictKeys, labels);
    }

    private static String toScopeArray(ErrorCode.Scope scope) {
        List<ErrorCode> scopedCodes = Arrays.stream(ErrorCode.values())
                .filter(errorCode -> errorCode.inScope(scope))
                .toList();
        if (scopedCodes.isEmpty()) {
            return "";
        }
        return scopedCodes.stream()
                .map(errorCode -> "  ERROR_KEYS." + errorCode.name() + ",")
                .collect(Collectors.joining("\n"));
    }

    private static String escapeTs(String value) {
        return value.replace("\\", "\\\\").replace("'", "\\'");
    }
}
