CREATE TABLE IF NOT EXISTS `sys_user_session` (
    `id`                varchar(36)  NOT NULL COMMENT '主键ID',
    `tenant_id`         varchar(36)           COMMENT '租户ID',
    `user_id`           varchar(36)  NOT NULL COMMENT '用户ID',
    `client_ip`         varchar(64)           COMMENT '客户端IP',
    `user_agent`        varchar(500)          COMMENT '浏览器UA',
    `device_name`       varchar(100)          COMMENT '设备名称',
    `login_time`        datetime              COMMENT '登录时间',
    `last_active_time`  datetime              COMMENT '最后活跃时间',
    `access_expires_at` datetime              COMMENT '访问令牌过期时间',
    `refresh_expires_at` datetime             COMMENT '刷新令牌过期时间',
    `status`            tinyint(1)   NOT NULL DEFAULT 1 COMMENT '状态:1在线 0离线',
    `logout_reason`     varchar(255)          COMMENT '下线原因',
    `logout_by`         varchar(50)           COMMENT '下线操作人',
    `logout_time`       datetime              COMMENT '下线时间',
    `del_flag`          tinyint(1)   NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`         varchar(50)           COMMENT '创建人',
    `create_time`       datetime              COMMENT '创建时间',
    `update_by`         varchar(50)           COMMENT '更新人',
    `update_time`       datetime              COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_user_session_user` (`user_id`),
    KEY `idx_user_session_tenant` (`tenant_id`),
    KEY `idx_user_session_status` (`status`),
    KEY `idx_user_session_refresh_exp` (`refresh_expires_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户登录会话';
