CREATE TABLE IF NOT EXISTS `ai_project` (
    `id`                   varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`            varchar(36)            COMMENT '租户ID',
    `project_code`         varchar(64)   NOT NULL COMMENT '项目编码',
    `project_name`         varchar(128)  NOT NULL COMMENT '项目名称',
    `project_type`         varchar(64)            COMMENT '项目类型',
    `intake_summary`       text                   COMMENT '需求摘要',
    `current_stage_code`   varchar(64)            COMMENT '当前阶段编码',
    `status`               varchar(32)   NOT NULL DEFAULT 'INTAKE' COMMENT '项目状态',
    `risk_level`           varchar(32)   NOT NULL DEFAULT 'MEDIUM' COMMENT '风险等级',
    `owner_user_id`        varchar(36)            COMMENT '负责人用户ID',
    `workflow_template_id` varchar(36)            COMMENT '工作流模板ID',
    `remark`               varchar(500)           COMMENT '备注',
    `del_flag`             tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`            varchar(50)            COMMENT '创建人',
    `create_time`          datetime               COMMENT '创建时间',
    `update_by`            varchar(50)            COMMENT '更新人',
    `update_time`          datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_project_tenant_code` (`tenant_id`, `project_code`),
    KEY `idx_ai_project_status` (`status`),
    KEY `idx_ai_project_owner` (`owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS项目';

CREATE TABLE IF NOT EXISTS `ai_project_stage` (
    `id`            varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`     varchar(36)            COMMENT '租户ID',
    `project_id`    varchar(36)   NOT NULL COMMENT '项目ID',
    `stage_code`    varchar(64)   NOT NULL COMMENT '阶段编码',
    `stage_name`    varchar(128)  NOT NULL COMMENT '阶段名称',
    `stage_order`   int           NOT NULL DEFAULT 0 COMMENT '阶段顺序',
    `stage_status`  varchar(32)   NOT NULL DEFAULT 'PENDING' COMMENT '阶段状态',
    `gate_status`   varchar(32)   NOT NULL DEFAULT 'PENDING' COMMENT '门禁状态',
    `owner_user_id` varchar(36)            COMMENT '阶段负责人用户ID',
    `started_at`    datetime               COMMENT '开始时间',
    `ended_at`      datetime               COMMENT '结束时间',
    `remark`        varchar(500)           COMMENT '备注',
    `del_flag`      tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`     varchar(50)            COMMENT '创建人',
    `create_time`   datetime               COMMENT '创建时间',
    `update_by`     varchar(50)            COMMENT '更新人',
    `update_time`   datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_project_stage_code` (`project_id`, `stage_code`),
    KEY `idx_ai_project_stage_project` (`project_id`),
    KEY `idx_ai_project_stage_status` (`stage_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS项目阶段';

CREATE TABLE IF NOT EXISTS `ai_decision_item` (
    `id`                   varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`            varchar(36)            COMMENT '租户ID',
    `project_id`           varchar(36)   NOT NULL COMMENT '项目ID',
    `project_stage_id`     varchar(36)            COMMENT '项目阶段ID',
    `title`                varchar(200)  NOT NULL COMMENT '决策标题',
    `item_type`            varchar(64)            COMMENT '决策类型',
    `source_type`          varchar(64)            COMMENT '来源类型',
    `source_id`            varchar(36)            COMMENT '来源ID',
    `description`          text                   COMMENT '决策描述',
    `impact_summary`       text                   COMMENT '影响摘要',
    `suggested_options`    text                   COMMENT '建议选项',
    `recommended_option`   varchar(255)           COMMENT '推荐选项',
    `budget_impact_summary` text                  COMMENT '预算影响摘要',
    `project_impact_summary` text                 COMMENT '项目影响摘要',
    `blocker_flag`         tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否阻塞',
    `priority`             varchar(32)   NOT NULL DEFAULT 'MEDIUM' COMMENT '优先级',
    `status`               varchar(32)   NOT NULL DEFAULT 'OPEN' COMMENT '状态',
    `requested_by_user_id` varchar(36)            COMMENT '发起人用户ID',
    `assignee_user_id`     varchar(36)            COMMENT '处理人用户ID',
    `due_at`               datetime               COMMENT '截止时间',
    `remark`               varchar(500)           COMMENT '备注',
    `del_flag`             tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`            varchar(50)            COMMENT '创建人',
    `create_time`          datetime               COMMENT '创建时间',
    `update_by`            varchar(50)            COMMENT '更新人',
    `update_time`          datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_decision_project` (`project_id`),
    KEY `idx_ai_decision_stage` (`project_stage_id`),
    KEY `idx_ai_decision_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS决策项';

CREATE TABLE IF NOT EXISTS `ai_approval_record` (
    `id`               varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`        varchar(36)            COMMENT '租户ID',
    `project_id`       varchar(36)            COMMENT '项目ID',
    `title`            varchar(200)           COMMENT '审批标题',
    `decision_item_id` varchar(36)            COMMENT '决策项ID',
    `approval_type`    varchar(64)   NOT NULL COMMENT '审批类型',
    `source_object_type` varchar(64)          COMMENT '来源对象类型',
    `source_object_id` varchar(36)            COMMENT '来源对象ID',
    `requester_user_id` varchar(36)           COMMENT '发起人用户ID',
    `approver_user_id` varchar(36)            COMMENT '审批人用户ID',
    `description`      text                   COMMENT '背景说明',
    `risk_summary`     text                   COMMENT '风险摘要',
    `budget_impact_summary` text              COMMENT '预算影响摘要',
    `recommended_action` varchar(255)         COMMENT '推荐动作',
    `blocker_flag`     tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否阻塞',
    `approval_status`  varchar(32)   NOT NULL DEFAULT 'submitted' COMMENT '审批状态',
    `operator_user_id` varchar(36)            COMMENT '最近操作人用户ID',
    `submitted_at`     datetime               COMMENT '提交时间',
    `decided_at`       datetime               COMMENT '决策时间',
    `decision_note`    varchar(500)           COMMENT '审批说明',
    `remark`           varchar(500)           COMMENT '备注',
    `del_flag`         tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`        varchar(50)            COMMENT '创建人',
    `create_time`      datetime               COMMENT '创建时间',
    `update_by`        varchar(50)            COMMENT '更新人',
    `update_time`      datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_approval_project` (`project_id`),
    KEY `idx_ai_approval_decision` (`decision_item_id`),
    KEY `idx_ai_approval_status` (`approval_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS审批记录';

CREATE TABLE IF NOT EXISTS `ai_budget_plan` (
    `id`              varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`       varchar(36)            COMMENT '租户ID',
    `project_id`      varchar(36)   NOT NULL COMMENT '项目ID',
    `plan_name`       varchar(128)  NOT NULL COMMENT '预算计划名称',
    `currency_code`   varchar(16)   NOT NULL DEFAULT 'TOKEN' COMMENT '预算单位',
    `proposed_amount` bigint        NOT NULL DEFAULT 0 COMMENT '提议预算',
    `approved_amount` bigint        NOT NULL DEFAULT 0 COMMENT '批准预算',
    `reserved_amount` bigint        NOT NULL DEFAULT 0 COMMENT '预留预算',
    `consumed_amount` bigint        NOT NULL DEFAULT 0 COMMENT '已消耗预算',
    `role_allocations_json` text             COMMENT '角色预算分配JSON',
    `status`          varchar(32)   NOT NULL DEFAULT 'DRAFT' COMMENT '预算状态',
    `effective_at`    datetime               COMMENT '生效时间',
    `remark`          varchar(500)           COMMENT '备注',
    `del_flag`        tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`       varchar(50)            COMMENT '创建人',
    `create_time`     datetime               COMMENT '创建时间',
    `update_by`       varchar(50)            COMMENT '更新人',
    `update_time`     datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_budget_plan_project` (`project_id`),
    KEY `idx_ai_budget_plan_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS预算计划';

CREATE TABLE IF NOT EXISTS `ai_budget_ledger` (
    `id`             varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`      varchar(36)            COMMENT '租户ID',
    `project_id`     varchar(36)   NOT NULL COMMENT '项目ID',
    `budget_plan_id` varchar(36)            COMMENT '预算计划ID',
    `entry_type`     varchar(32)   NOT NULL COMMENT '流水类型',
    `amount`         bigint        NOT NULL DEFAULT 0 COMMENT '变动金额',
    `balance_after`  bigint        NOT NULL DEFAULT 0 COMMENT '变动后余额',
    `reference_type` varchar(64)            COMMENT '关联类型',
    `reference_id`   varchar(36)            COMMENT '关联ID',
    `occurred_at`    datetime               COMMENT '发生时间',
    `description`    varchar(500)           COMMENT '说明',
    `remark`         varchar(500)           COMMENT '备注',
    `del_flag`       tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`      varchar(50)            COMMENT '创建人',
    `create_time`    datetime               COMMENT '创建时间',
    `update_by`      varchar(50)            COMMENT '更新人',
    `update_time`    datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_budget_ledger_project` (`project_id`),
    KEY `idx_ai_budget_ledger_plan` (`budget_plan_id`),
    KEY `idx_ai_budget_ledger_type` (`entry_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS预算流水';

CREATE TABLE IF NOT EXISTS `ai_agent_role` (
    `id`                 varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`          varchar(36)            COMMENT '租户ID',
    `role_code`          varchar(64)   NOT NULL COMMENT '角色编码',
    `role_name`          varchar(128)  NOT NULL COMMENT '角色名称',
    `role_category`      varchar(64)            COMMENT '角色分类',
    `description`        text                   COMMENT '角色描述',
    `status`             varchar(32)   NOT NULL DEFAULT 'active' COMMENT '状态',
    `capability_summary` varchar(500)           COMMENT '能力摘要',
    `default_flag`       tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否默认角色',
    `budget_factor`      decimal(10,2) NOT NULL DEFAULT 1.00 COMMENT '预算系数',
    `approval_collaboration_flag` tinyint(1) NOT NULL DEFAULT 1 COMMENT '审批协作标记',
    `approval_required`  tinyint(1)    NOT NULL DEFAULT 1 COMMENT '是否需要审批',
    `max_concurrency`    int           NOT NULL DEFAULT 1 COMMENT '最大并发任务数',
    `remark`             varchar(500)           COMMENT '备注',
    `del_flag`           tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`          varchar(50)            COMMENT '创建人',
    `create_time`        datetime               COMMENT '创建时间',
    `update_by`          varchar(50)            COMMENT '更新人',
    `update_time`        datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_agent_role_code` (`tenant_id`, `role_code`),
    KEY `idx_ai_agent_role_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS代理角色';

CREATE TABLE IF NOT EXISTS `ai_agent_role_stage_participation` (
    `id`                 varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`          varchar(36)            COMMENT '租户ID',
    `agent_role_id`      varchar(36)   NOT NULL COMMENT '角色ID',
    `stage_code`         varchar(64)   NOT NULL COMMENT '阶段编码',
    `stage_name`         varchar(128)           COMMENT '阶段名称',
    `participation_type` varchar(32)   NOT NULL DEFAULT 'not_involved' COMMENT '参与类型',
    `note`               varchar(500)           COMMENT '备注',
    `del_flag`           tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`          varchar(50)            COMMENT '创建人',
    `create_time`        datetime               COMMENT '创建时间',
    `update_by`          varchar(50)            COMMENT '更新人',
    `update_time`        datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_agent_role_stage` (`agent_role_id`, `stage_code`),
    KEY `idx_ai_agent_role_stage_role` (`agent_role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS角色阶段参与';

CREATE TABLE IF NOT EXISTS `ai_agent_role_allowed_action` (
    `id`                     varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`              varchar(36)            COMMENT '租户ID',
    `agent_role_id`          varchar(36)   NOT NULL COMMENT '角色ID',
    `action_code`            varchar(64)   NOT NULL COMMENT '动作编码',
    `action_name`            varchar(128)           COMMENT '动作名称',
    `allowed_flag`           tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否允许',
    `approval_required_flag` tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否需要审批',
    `note`                   varchar(500)           COMMENT '备注',
    `del_flag`               tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`              varchar(50)            COMMENT '创建人',
    `create_time`            datetime               COMMENT '创建时间',
    `update_by`              varchar(50)            COMMENT '更新人',
    `update_time`            datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_agent_role_action` (`agent_role_id`, `action_code`),
    KEY `idx_ai_agent_role_action_role` (`agent_role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS角色允许动作';

CREATE TABLE IF NOT EXISTS `ai_workflow_template` (
    `id`            varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`     varchar(36)            COMMENT '租户ID',
    `template_code` varchar(64)   NOT NULL COMMENT '模板编码',
    `template_name` varchar(128)  NOT NULL COMMENT '模板名称',
    `project_type`  varchar(64)            COMMENT '项目类型',
    `version_no`    int           NOT NULL DEFAULT 1 COMMENT '版本号',
    `stage_count`   int           NOT NULL DEFAULT 0 COMMENT '阶段数量',
    `status`        varchar(32)   NOT NULL DEFAULT 'DRAFT' COMMENT '状态',
    `default_flag`  tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否默认模板',
    `description`   varchar(500)           COMMENT '描述',
    `gate_checks_config` text               COMMENT 'Gate检查配置',
    `blocking_decision_config` text         COMMENT '阻塞决策条件',
    `blocking_approval_config` text         COMMENT '阻塞审批条件',
    `budget_threshold_config` text          COMMENT '预算阈值条件',
    `high_risk_approval_config` text        COMMENT '高风险动作审批要求',
    `remark`        varchar(500)           COMMENT '备注',
    `del_flag`      tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`     varchar(50)            COMMENT '创建人',
    `create_time`   datetime               COMMENT '创建时间',
    `update_by`     varchar(50)            COMMENT '更新人',
    `update_time`   datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_workflow_template_code` (`tenant_id`, `template_code`),
    KEY `idx_ai_workflow_template_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS工作流模板';

CREATE TABLE IF NOT EXISTS `ai_workflow_template_stage` (
    `id`                varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`         varchar(36)            COMMENT '租户ID',
    `template_id`       varchar(36)   NOT NULL COMMENT '模板ID',
    `stage_code`        varchar(64)   NOT NULL COMMENT '阶段编码',
    `stage_name`        varchar(128)  NOT NULL COMMENT '阶段名称',
    `stage_order`       int           NOT NULL DEFAULT 0 COMMENT '阶段顺序',
    `enabled_flag`      tinyint(1)    NOT NULL DEFAULT 1 COMMENT '是否启用',
    `stage_description` text                   COMMENT '阶段描述',
    `stage_note`        varchar(500)           COMMENT '阶段备注',
    `del_flag`          tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`         varchar(50)            COMMENT '创建人',
    `create_time`       datetime               COMMENT '创建时间',
    `update_by`         varchar(50)            COMMENT '更新人',
    `update_time`       datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_workflow_template_stage` (`template_id`, `stage_code`),
    KEY `idx_ai_workflow_template_stage_tid` (`template_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS工作流模板阶段';

CREATE TABLE IF NOT EXISTS `ai_requirement_intake` (
    `id`                      varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`               varchar(36)            COMMENT '租户ID',
    `project_id`              varchar(36)   NOT NULL COMMENT '项目ID',
    `project_name`            varchar(128)           COMMENT '项目名称',
    `project_type`            varchar(64)            COMMENT '项目类型',
    `business_goal`           text                   COMMENT '业务目标',
    `feature_summary`         text                   COMMENT '功能摘要',
    `reference_products`      text                   COMMENT '参考产品或链接',
    `timeline_expectation`    varchar(255)           COMMENT '时间预期',
    `budget_range`            varchar(255)           COMMENT '预算范围',
    `technical_constraints`   text                   COMMENT '技术约束',
    `notes`                   text                   COMMENT '补充说明',
    `attachment_placeholders` text                   COMMENT '附件占位',
    `del_flag`                tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`               varchar(50)            COMMENT '创建人',
    `create_time`             datetime               COMMENT '创建时间',
    `update_by`               varchar(50)            COMMENT '更新人',
    `update_time`             datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_requirement_project` (`project_id`),
    KEY `idx_ai_requirement_tenant_project` (`tenant_id`, `project_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS需求接收';

CREATE TABLE IF NOT EXISTS `ai_clarification_item` (
    `id`                varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`         varchar(36)            COMMENT '租户ID',
    `project_id`        varchar(36)   NOT NULL COMMENT '项目ID',
    `title`             varchar(200)  NOT NULL COMMENT '澄清标题',
    `question`          text                   COMMENT '澄清问题',
    `category`          varchar(64)            COMMENT '分类',
    `severity`          varchar(32)   NOT NULL DEFAULT 'medium' COMMENT '严重等级',
    `suggested_options` text                   COMMENT '建议选项',
    `user_response`     text                   COMMENT '用户回复',
    `status`            varchar(32)   NOT NULL DEFAULT 'open' COMMENT '状态',
    `generated_flag`    tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否为生成项',
    `promoted_decision_item_id` varchar(36)    COMMENT '已转化的决策项ID',
    `remark`            varchar(500)           COMMENT '备注',
    `del_flag`          tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`         varchar(50)            COMMENT '创建人',
    `create_time`       datetime               COMMENT '创建时间',
    `update_by`         varchar(50)            COMMENT '更新人',
    `update_time`       datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_clarification_project` (`project_id`),
    KEY `idx_ai_clarification_status` (`status`),
    KEY `idx_ai_clarification_severity` (`severity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS澄清项';

CREATE TABLE IF NOT EXISTS `ai_decision_action_log` (
    `id`               varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`        varchar(36)            COMMENT '租户ID',
    `decision_item_id` varchar(36)   NOT NULL COMMENT '决策事项ID',
    `action_type`      varchar(32)   NOT NULL COMMENT '动作类型',
    `action_comment`   text                   COMMENT '动作说明',
    `previous_status`  varchar(32)            COMMENT '原状态',
    `next_status`      varchar(32)            COMMENT '目标状态',
    `operator_user_id` varchar(36)            COMMENT '操作人用户ID',
    `operated_at`      datetime               COMMENT '操作时间',
    `del_flag`         tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`        varchar(50)            COMMENT '创建人',
    `create_time`      datetime               COMMENT '创建时间',
    `update_by`        varchar(50)            COMMENT '更新人',
    `update_time`      datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_decision_action_decision` (`decision_item_id`),
    KEY `idx_ai_decision_action_operated` (`operated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS决策动作日志';

CREATE TABLE IF NOT EXISTS `ai_approval_action_log` (
    `id`               varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`        varchar(36)            COMMENT '租户ID',
    `approval_record_id` varchar(36) NOT NULL COMMENT '审批记录ID',
    `action_type`      varchar(32)   NOT NULL COMMENT '动作类型',
    `action_comment`   text                   COMMENT '动作说明',
    `previous_status`  varchar(32)            COMMENT '原状态',
    `next_status`      varchar(32)            COMMENT '目标状态',
    `operator_user_id` varchar(36)            COMMENT '操作人用户ID',
    `operated_at`      datetime               COMMENT '操作时间',
    `del_flag`         tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`        varchar(50)            COMMENT '创建人',
    `create_time`      datetime               COMMENT '创建时间',
    `update_by`        varchar(50)            COMMENT '更新人',
    `update_time`      datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_approval_action_record` (`approval_record_id`),
    KEY `idx_ai_approval_action_operated` (`operated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS审批动作日志';

CREATE TABLE IF NOT EXISTS `ai_meeting_record` (
    `id`                     varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`              varchar(36)            COMMENT '租户ID',
    `project_id`             varchar(36)   NOT NULL COMMENT '项目ID',
    `meeting_title`          varchar(200)           COMMENT '会议标题',
    `raw_notes`              text                   COMMENT '原始笔记',
    `summary`                text                   COMMENT '总结',
    `action_items_json`      text                   COMMENT '行动项JSON',
    `open_questions_json`    text                   COMMENT '开放问题JSON',
    `decision_candidates_json` text                 COMMENT '决策候选JSON',
    `source_type`            varchar(64)            COMMENT '来源类型',
    `source_object_id`       varchar(36)            COMMENT '来源对象ID',
    `generated_by`           varchar(36)            COMMENT '生成人',
    `generated_at`           datetime               COMMENT '生成时间',
    `remark`                 varchar(500)           COMMENT '备注',
    `del_flag`               tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`              varchar(50)            COMMENT '创建人',
    `create_time`            datetime               COMMENT '创建时间',
    `update_by`              varchar(50)            COMMENT '更新人',
    `update_time`            datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_meeting_record_project` (`project_id`),
    KEY `idx_ai_meeting_record_generated_at` (`generated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS会议记录';

CREATE TABLE IF NOT EXISTS `ai_project_governance_state` (
    `id`                           varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`                    varchar(36)            COMMENT '租户ID',
    `project_id`                   varchar(36)   NOT NULL COMMENT '项目ID',
    `current_stage_code`           varchar(64)            COMMENT '当前阶段编码',
    `current_stage_name`           varchar(128)           COMMENT '当前阶段名称',
    `current_stage_status`         varchar(32)            COMMENT '当前阶段状态',
    `current_gate_status`          varchar(32)            COMMENT '当前门禁状态',
    `governance_status`            varchar(32)   NOT NULL DEFAULT 'healthy' COMMENT '治理状态',
    `blocked_flag`                 tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否阻塞',
    `at_risk_flag`                 tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否风险',
    `pending_decision_count`       int           NOT NULL DEFAULT 0 COMMENT '待处理决策数',
    `blocker_decision_count`       int           NOT NULL DEFAULT 0 COMMENT '阻塞决策数',
    `pending_approval_count`       int           NOT NULL DEFAULT 0 COMMENT '待处理审批数',
    `blocker_approval_count`       int           NOT NULL DEFAULT 0 COMMENT '阻塞审批数',
    `clarification_count`          int           NOT NULL DEFAULT 0 COMMENT '澄清项总数',
    `blocker_clarification_count`  int           NOT NULL DEFAULT 0 COMMENT '阻塞澄清项数',
    `failed_gate_condition_count`  int           NOT NULL DEFAULT 0 COMMENT '失败门禁条件数',
    `blocking_gate_condition_count` int          NOT NULL DEFAULT 0 COMMENT '阻塞门禁条件数',
    `missing_critical_role_count`  int           NOT NULL DEFAULT 0 COMMENT '缺失关键角色数',
    `budget_status`                varchar(32)            COMMENT '预算健康状态',
    `blocker_reason_summary`       varchar(500)           COMMENT '治理原因摘要',
    `last_recomputed_at`           datetime               COMMENT '最近重算时间',
    `del_flag`                     tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`                    varchar(50)            COMMENT '创建人',
    `create_time`                  datetime               COMMENT '创建时间',
    `update_by`                    varchar(50)            COMMENT '更新人',
    `update_time`                  datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ai_project_governance_project` (`project_id`),
    KEY `idx_ai_project_governance_status` (`governance_status`),
    KEY `idx_ai_project_governance_blocked` (`blocked_flag`),
    KEY `idx_ai_project_governance_risk` (`at_risk_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS项目治理状态快照';

CREATE TABLE IF NOT EXISTS `ai_project_tool_binding` (
    `id`              varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`       varchar(36)            COMMENT '租户ID',
    `project_id`      varchar(36)   NOT NULL COMMENT '项目ID',
    `tool_type`       varchar(32)   NOT NULL COMMENT '工具类型',
    `binding_type`    varchar(32)   NOT NULL COMMENT '绑定类型',
    `external_id`     varchar(128)           COMMENT '外部对象ID',
    `external_key`    varchar(255)           COMMENT '外部对象键',
    `external_name`   varchar(255)           COMMENT '外部对象名称',
    `external_url`    varchar(500)           COMMENT '外部对象URL',
    `binding_status`  varchar(32)   NOT NULL DEFAULT 'linked' COMMENT '绑定状态',
    `default_flag`    tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否默认绑定',
    `metadata_json`   text                   COMMENT '元数据JSON',
    `remark`          varchar(500)           COMMENT '备注',
    `del_flag`        tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`       varchar(50)            COMMENT '创建人',
    `create_time`     datetime               COMMENT '创建时间',
    `update_by`       varchar(50)            COMMENT '更新人',
    `update_time`     datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_project_tool_binding_project` (`project_id`),
    KEY `idx_ai_project_tool_binding_tool` (`tool_type`, `binding_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS项目工具绑定';

CREATE TABLE IF NOT EXISTS `ai_tool_integration_audit` (
    `id`                  varchar(36)   NOT NULL COMMENT '主键ID',
    `tenant_id`           varchar(36)            COMMENT '租户ID',
    `project_id`          varchar(36)            COMMENT '项目ID',
    `tool_type`           varchar(32)   NOT NULL COMMENT '工具类型',
    `action_type`         varchar(64)   NOT NULL COMMENT '动作类型',
    `source_object_type`  varchar(64)            COMMENT '来源对象类型',
    `source_object_id`    varchar(36)            COMMENT '来源对象ID',
    `binding_id`          varchar(36)            COMMENT '项目工具绑定ID',
    `preview_flag`        tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否预览',
    `confirmed_flag`      tinyint(1)    NOT NULL DEFAULT 0 COMMENT '是否确认执行',
    `audit_status`        varchar(32)   NOT NULL DEFAULT 'previewed' COMMENT '审计状态',
    `request_payload_json`  text                 COMMENT '请求载荷JSON',
    `response_payload_json` text                 COMMENT '响应载荷JSON',
    `external_object_id`  varchar(128)           COMMENT '外部对象ID',
    `external_object_url` varchar(500)           COMMENT '外部对象URL',
    `operator_user_id`    varchar(36)            COMMENT '操作人用户ID',
    `error_message`       varchar(500)           COMMENT '错误信息',
    `del_flag`            tinyint(1)    NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`           varchar(50)            COMMENT '创建人',
    `create_time`         datetime               COMMENT '创建时间',
    `update_by`           varchar(50)            COMMENT '更新人',
    `update_time`         datetime               COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_ai_tool_integration_audit_project` (`project_id`, `create_time`),
    KEY `idx_ai_tool_integration_audit_tool` (`tool_type`, `action_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AICoOS工具集成审计';
