CREATE TABLE IF NOT EXISTS `sys_system_config` (
    `id`            varchar(36)  NOT NULL COMMENT '主键ID',
    `tenant_id`     varchar(36)           COMMENT '租户ID，为空表示平台级配置',
    `group_code`    varchar(64)  NOT NULL COMMENT '分组编码',
    `group_name`    varchar(100) NOT NULL COMMENT '分组名称',
    `group_sort`    int          NOT NULL DEFAULT 0 COMMENT '分组排序',
    `config_key`    varchar(128) NOT NULL COMMENT '配置键',
    `config_name`   varchar(100) NOT NULL COMMENT '配置名称',
    `config_value`  text                  COMMENT '配置值',
    `default_value` text                  COMMENT '默认值',
    `value_type`    varchar(32)  NOT NULL DEFAULT 'text' COMMENT '值类型:text/textarea/number/boolean/color/url/email',
    `required_flag` tinyint(1)   NOT NULL DEFAULT 0 COMMENT '是否必填',
    `placeholder`   varchar(255)          COMMENT '占位提示',
    `description`   varchar(500)          COMMENT '说明',
    `options_json`  text                  COMMENT '选项JSON',
    `sort_no`       int          NOT NULL DEFAULT 0 COMMENT '组内排序',
    `built_in`      tinyint(1)   NOT NULL DEFAULT 1 COMMENT '是否内置',
    `status`        tinyint(1)   NOT NULL DEFAULT 1 COMMENT '状态',
    `del_flag`      tinyint(1)   NOT NULL DEFAULT 0 COMMENT '删除状态',
    `create_by`     varchar(50)           COMMENT '创建人',
    `create_time`   datetime              COMMENT '创建时间',
    `update_by`     varchar(50)           COMMENT '更新人',
    `update_time`   datetime              COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_system_config_tenant_key` (`tenant_id`,`config_key`),
    KEY `idx_system_config_group` (`group_code`, `group_sort`),
    KEY `idx_system_config_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统配置表';

SET @now = NOW();

INSERT INTO `sys_system_config` (
    `id`, `tenant_id`, `group_code`, `group_name`, `group_sort`, `config_key`, `config_name`,
    `config_value`, `default_value`, `value_type`, `required_flag`, `placeholder`, `description`,
    `options_json`, `sort_no`, `built_in`, `status`, `del_flag`, `create_by`, `create_time`,
    `update_by`, `update_time`
) VALUES
    ('cfg_site_name', NULL, 'branding', '品牌信息', 10, 'branding.siteName', '站点名称', 'SaaS Admin Template', 'SaaS Admin Template', 'text', 1, '请输入站点名称', '用于登录页标题、后台页头与品牌展示。', NULL, 11, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_site_subtitle', NULL, 'branding', '品牌信息', 10, 'branding.siteSubtitle', '站点副标题', '开箱即用的 SaaS 后台管理模板', '开箱即用的 SaaS 后台管理模板', 'textarea', 0, '请输入站点副标题', '用于登录页与平台简介说明。', NULL, 12, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_brand_logo', NULL, 'branding', '品牌信息', 10, 'branding.logoUrl', 'Logo 地址', '/logo.svg', '/logo.svg', 'url', 0, '请输入 Logo 地址', '支持填写相对路径或完整 URL。', NULL, 13, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_brand_primary_color', NULL, 'branding', '品牌信息', 10, 'branding.primaryColor', '品牌主色', '#1677ff', '#1677ff', 'color', 0, '#1677ff', '用于后续主题与品牌色配置。', NULL, 14, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_copyright_text', NULL, 'branding', '品牌信息', 10, 'branding.copyrightText', '版权文案', 'SaaS Admin Template 版权所有', 'SaaS Admin Template 版权所有', 'text', 0, '请输入版权文案', '用于页脚版权展示。', NULL, 15, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_password_min_length', NULL, 'security', '安全策略', 20, 'security.password.minLength', '密码最小长度', '8', '8', 'number', 1, '请输入最小长度', '影响注册、重置密码和修改密码的校验。', NULL, 21, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_password_max_length', NULL, 'security', '安全策略', 20, 'security.password.maxLength', '密码最大长度', '32', '32', 'number', 1, '请输入最大长度', '影响注册、重置密码和修改密码的校验。', NULL, 22, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_password_require_uppercase', NULL, 'security', '安全策略', 20, 'security.password.requireUppercase', '要求大写字母', 'true', 'true', 'boolean', 1, NULL, '密码是否必须包含大写字母。', NULL, 23, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_password_require_lowercase', NULL, 'security', '安全策略', 20, 'security.password.requireLowercase', '要求小写字母', 'true', 'true', 'boolean', 1, NULL, '密码是否必须包含小写字母。', NULL, 24, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_password_require_digit', NULL, 'security', '安全策略', 20, 'security.password.requireDigit', '要求数字', 'true', 'true', 'boolean', 1, NULL, '密码是否必须包含数字。', NULL, 25, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_password_require_special', NULL, 'security', '安全策略', 20, 'security.password.requireSpecial', '要求特殊字符', 'true', 'true', 'boolean', 1, NULL, '密码是否必须包含特殊字符。', NULL, 26, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_jwt_exp_seconds', NULL, 'security', '安全策略', 20, 'security.jwt.expSeconds', '访问令牌时长(秒)', '3600', '3600', 'number', 1, '请输入秒数', '用于前端展示当前访问令牌的默认时长。', NULL, 27, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_jwt_refresh_exp_seconds', NULL, 'security', '安全策略', 20, 'security.jwt.refreshExpSeconds', '刷新令牌时长(秒)', '1209600', '1209600', 'number', 1, '请输入秒数', '用于前端展示当前刷新令牌的默认时长。', NULL, 28, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_file_max_size_mb', NULL, 'file', '文件策略', 30, 'file.maxSizeMb', '文件大小上限(MB)', '20', '20', 'number', 1, '请输入 MB 数', '文件上传会按此限制大小。', NULL, 31, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_file_allowed_types', NULL, 'file', '文件策略', 30, 'file.allowedTypes', '允许上传类型', '.png,.jpg,.jpeg,.pdf,.doc,.docx,.xls,.xlsx,.zip', '.png,.jpg,.jpeg,.pdf,.doc,.docx,.xls,.xlsx,.zip', 'textarea', 0, '请输入扩展名，逗号分隔', '用于前端上传提示与后端扩展名校验。', NULL, 32, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_file_default_biz_type', NULL, 'file', '文件策略', 30, 'file.defaultBizType', '默认业务类型', 'system', 'system', 'text', 0, '请输入默认业务类型', '上传文件时未指定业务类型的默认值。', NULL, 33, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_file_storage_provider', NULL, 'file', '文件策略', 30, 'file.storageProvider', '存储提供方', 'local', 'local', 'text', 0, '请输入存储提供方', '用于展示当前文件中心默认存储提供方。', NULL, 34, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_notify_email_from_name', NULL, 'notification', '通知配置', 40, 'notification.email.fromName', '邮件发送者名称', 'SaaS Admin', 'SaaS Admin', 'text', 0, '请输入邮件发送者名称', '用于后续邮件通知模块扩展。', NULL, 41, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_notify_email_from_address', NULL, 'notification', '通知配置', 40, 'notification.email.fromAddress', '邮件发送地址', 'no-reply@example.com', 'no-reply@example.com', 'email', 0, '请输入邮件发送地址', '用于后续邮件通知模块扩展。', NULL, 42, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_notify_sms_sign', NULL, 'notification', '通知配置', 40, 'notification.sms.sign', '短信签名', 'SaaS后台', 'SaaS后台', 'text', 0, '请输入短信签名', '用于后续短信通知模块扩展。', NULL, 43, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now),
    ('cfg_notify_webhook_url', NULL, 'notification', '通知配置', 40, 'notification.webhook.url', 'Webhook 地址', '', '', 'url', 0, '请输入 Webhook 地址', '用于后续系统告警或站外通知扩展。', NULL, 44, 1, 1, 0, 'bootstrap', @now, 'bootstrap', @now)
ON DUPLICATE KEY UPDATE
    `group_code` = VALUES(`group_code`),
    `group_name` = VALUES(`group_name`),
    `group_sort` = VALUES(`group_sort`),
    `config_key` = VALUES(`config_key`),
    `config_name` = VALUES(`config_name`),
    `default_value` = VALUES(`default_value`),
    `value_type` = VALUES(`value_type`),
    `required_flag` = VALUES(`required_flag`),
    `placeholder` = VALUES(`placeholder`),
    `description` = VALUES(`description`),
    `options_json` = VALUES(`options_json`),
    `sort_no` = VALUES(`sort_no`),
    `built_in` = VALUES(`built_in`),
    `status` = VALUES(`status`),
    `del_flag` = 0,
    `update_by` = VALUES(`update_by`),
    `update_time` = VALUES(`update_time`);
